FROM debian:buster

ARG architecture=arm64
ARG node_version=14.12.0
ARG build_date
ARG repo=redloro
ARG branch=master

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="smartthings_nodeproxy_evl" \
      org.label-schema.description="SmartThings Node Proxy EVL for Docker" \
      org.label-schema.version="1.0.0" \
      org.label-schema.docker.cmd="docker run -d -p 54240:54240 -e ENABLED_PLUGINS='envisalink' smartthings_nodeproxy_evl:latest" \
      org.label-schema.build-date=$build_date \
      architecture=$architecture

RUN apt-get update
RUN apt-get install -y wget tar
RUN apt-get clean
RUN wget -O - https://nodejs.org/dist/v${node_version}/node-v${node_version}-linux-${architecture}.tar.gz \
  | tar -zxvf - --wildcards --strip-components=1 -C /usr/local/
RUN apt-get remove -y --auto-remove wget --purge
RUN rm -rf /tmp/* 

ENV NODE=/usr/local/bin/node
ENV NPM=/usr/local/bin/npm
ENV PYTHON=/usr/bin/python2.7

RUN apt-get install -y python2.7 build-essential libpcap-dev wget tar \
 && mkdir -p /stnp/plugins \
 && wget -O - https://github.com/${repo}/smartthings/tarball/${branch} \
  | tar -zxvf - --wildcards --strip-components=2 -C /stnp/ ${repo}-smartthings-*/smartthings-nodeproxy/ \
 && wget -O - https://github.com/${repo}/smartthings/tarball/${branch} \
  | tar -zxvf - --wildcards --strip-components=2 -C /tmp/ ${repo}-smartthings-*/docker/ \
 && cp /tmp/config.sample /stnp/config.json \
 && cp /tmp/docker-entrypoint.sh /docker-entrypoint.sh \
 && rm -rf /tmp/* \
 && cd /stnp \
 && rm -f restart.me smartthings-nodeproxy.service config.json \
 && npm install \
 && apt-get remove -y --auto-remove wget build-essential libpcap-dev libpcap0.8-dev --purge \
 && apt-get clean 

EXPOSE 54240

ENTRYPOINT ["/docker-entrypoint.sh"]
